### ISSUE TITLE
where is intersphinx inventory under new website domain?

### ISSUE THREAD

**Issue by drammock** [nipy/dipy#1955]
## Description
In the recent move from https://nipy.org/dipy to https://dipy.org, your `objects.inv` file has gone missing, which means we (MNE-Python) can't cross-reference your docs using intersphinx anymore. Our CircleCI doc tests now fail with 
```
intersphinx inventory 'http://nipy.org/dipy/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request for url: https://dipy.org/objects.inv
```
What is the new URL of your `objects.inv` file, so we can update our intersphinx mapping?

cc mne-tools/mne-python#6671

**Comment by larsoner** [comment]
I would have expected it to live in https://dipy.org/documentation/1.0.0./reference/objects.inv or https://dipy.org/documentation/1.0.0./objects.inv. I think there is some systematic problem here because all three links under this heading (Index, Module Index, Search Page) are broken:

https://dipy.org/documentation/1.0.0./documentation/#indices-and-tables

Maybe in moving the website not everything was copied?

**Comment by skoudoro** [comment]
> I would have expected it to live in https://dipy.org/documentation/1.0.0./reference/objects.inv or https://dipy.org/documentation/1.0.0./objects.inv. I think there is some systematic problem here because all three links under this heading (Index, Module Index, Search Page) are broken

I agree, I would expect the same, I will look deeper to see what happens. Thank you for the notification

**Comment by skoudoro** [comment]
Hi @drammock and @larsoner,

it should work now on: [https://dipy.org/documentation/1.0.0./objects.inv](https://dipy.org/documentation/1.0.0./objects.inv) or [https://dipy.org/documentation/latest/objects.inv](https://dipy.org/documentation/latest/objects.inv)

Sorry for the late fix

**Comment by drammock** [comment]
thanks @skoudoro, our doc builds are green again :slightly_smiling_face:

**Comment by larsoner** [comment]
It appears there is still a problem with the redirect:
```
https://dipy.org/documentation/latest/objects.inv -> https://dipy.org/documentation/1.0.0./objects.inv/
```
This trailing slash causes [our links](https://mne.tools/dev/generated/mne.SourceMorph.html#mne.SourceMorph) to look like:

https://dipy.org/documentation/1.0.0./objects.inv/reference/dipy.align/#dipy.align.imaffine.AffineMap

For now we will work around it by linking to the `1.0.0.` URL, but it would be nice at some point to link to `latest` instead.

**Comment by larsoner** [comment]
Actually even using the `1.0.0.` I get:
```
intersphinx inventory has moved: https://dipy.org/documentation/1.0.0./objects.inv -> https://dipy.org/documentation/1.0.0./objects.inv/
```

**Comment by larsoner** [comment]
This workaround works in the meantime:
```
    'dipy': ('https://dipy.org/documentation/latest',
             'https://dipy.org/documentation/1.0.0./objects.inv/'),
```

**Comment by skoudoro** [comment]
Hi @larsoner, I do not understand your original question concerning the problem with `redirect`.

I saw that you fix it, but I would like to make sure that there is a hidden problem

ps: Sorry for the late answer

**Comment by larsoner** [comment]
The URL:
```
https://dipy.org/documentation/1.0.0./objects.inv
```
Redirects to:
```
https://dipy.org/documentation/1.0.0./objects.inv/
```
To see it using `wget`:
```
$ wget https://dipy.org/documentation/1.0.0./objects.inv
--2019-09-04 14:23:44--  https://dipy.org/documentation/1.0.0./objects.inv
Resolving dipy.org (dipy.org)... 156.56.83.29
Connecting to dipy.org (dipy.org)|156.56.83.29|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /documentation/1.0.0./objects.inv/ [following]
--2019-09-04 14:23:46--  https://dipy.org/documentation/1.0.0./objects.inv/
...
```
This is a problem because, even though the inventory downloads, links are rendered by Sphinx *with objects.inv/ in the path*, such as the following (broken) link:

https://dipy.org/documentation/1.0.0./objects.inv/reference/dipy.align/#dipy.align.imaffine.AffineMap

When in a correctly working setup it should point here (note the lack of `objects.inv/` in the URL):

https://dipy.org/documentation/1.0.0./reference/dipy.align/#dipy.align.imaffine.AffineMap

**Comment by larsoner** [comment]
(In other words, I think you have some server misconfiguration that is breaking `intersphinx` by default, but can be worked around by end-users such as us using the fix above)

**Comment by skoudoro** [comment]
Ok, Thank you for the clear explanation!

will look into it.
